imports_granularity = "crate"
reorder_impl_items = true
group_imports = "StdExternalCrate"
wrap_comments = true
imports_layout = "HorizontalVertical"
# max_width = 200
# error_on_line_overflow = true

use_field_init_shorthand = true
format_macro_matchers = true
overflow_delimited_expr = true
